[project]
name = "simple-mcp-server-remote"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.12.4",
    "aiosqlite">=0.21.0"
]
